name: Publish Package

on:
  push:
    tags:
      - "v*.*.*" # Triggers on version tags, e.g., "v1.0.0"
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel twine

      - name: Build wheels with cibuildwheel
        env:
          CIBW_BUILD: "cp37-* cp38-* cp39-* cp310-*" # Choose specific Python versions if needed
          CIBW_SKIP: "pp*" # Skip PyPy builds (optional)
        run: |
          cibuildwheel --output-dir dist

      - name: Publish to PyPI
        if: github.ref_type == 'tag' || github.event_name == 'workflow_dispatch'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*
