name: Publish Package

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          # python-version: "3.x"
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel twine cython

      - name: Build wheels with cibuildwheel
        env:
          # CIBW_BUILD: "cp37-* cp38-* cp39-* cp310-*"
          CIBW_BUILD: "cp311-*"
        run: |
          cibuildwheel --output-dir dist

      - name: List contents of the dist folder
        # List the contents of the dist folder for debugging
        run: |
          echo "Listing contents of the dist directory:"
          find dist -type f

      - name: Remove Python source files from the wheel
        run: |
          find dist -type f -name "*.py" -delete
          find dist -type f -name "*.pyc" -delete

      - name: Publish to PyPI
        if: github.ref_type == 'tag' || github.event_name == 'workflow_dispatch'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*
